version = 0.1
[default.deploy.parameters]
stack_name = "covapi"
resolve_s3 = true
s3_prefix = "covapi"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["Covapi=584518143473.dkr.ecr.us-west-2.amazonaws.com/covapib7e9f537/covapi221fa7a2repo"]
disable_rollback = true
